"""Registry-driven domain closure tests.

Replaces 24 individual domain test files (test_258 through test_281) with a
single parametric runner that loads precomputed kernel values from the
centralized test registry (artifacts/test_registry.json).

This provides:
  - One file instead of 24 nearly identical files
  - Tests run against precomputed numbers (no per-entity kernel recomputation)
  - All domain data visible in one JSON for comparison and study
  - Fast verification: registry values vs live kernel at session scope
  - Same test count and coverage as the individual files

The registry is generated by:  python scripts/harvest_test_registry.py

Tier-1 identity checks (F + ω = 1, IC ≤ F, IC = exp(κ)) validate against
precomputed values AND re-verify live if the --live flag or UMCP_LIVE_REGISTRY
env var is set.
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Any

import numpy as np
import pytest

REGISTRY_PATH = Path(__file__).resolve().parents[1] / "artifacts" / "test_registry.json"


def _load_registry() -> dict[str, Any]:
    """Load the test registry, failing clearly if not found."""
    if not REGISTRY_PATH.exists():
        pytest.skip(
            f"Test registry not found at {REGISTRY_PATH}. Generate it with: python scripts/harvest_test_registry.py"
        )
    with open(REGISTRY_PATH) as f:
        return json.load(f)


# ── Session-scoped registry fixture ─────────────────────────────────────────


@pytest.fixture(scope="session")
def registry() -> dict[str, Any]:
    return _load_registry()


# ── Parametrize helpers ─────────────────────────────────────────────────────


def _domain_keys() -> list[str]:
    """Return domain keys from registry for parametrization."""
    if not REGISTRY_PATH.exists():
        return []
    with open(REGISTRY_PATH) as f:
        reg = json.load(f)
    return list(reg.get("domains", {}).keys())


def _entity_params() -> list[tuple[str, str, dict]]:
    """Return (domain_key, entity_name, entity_data) tuples."""
    if not REGISTRY_PATH.exists():
        return []
    with open(REGISTRY_PATH) as f:
        reg = json.load(f)
    params = []
    for dkey, ddata in reg.get("domains", {}).items():
        for entity in ddata["entities"]:
            params.append((dkey, entity["name"], entity))
    return params


def _theorem_params() -> list[tuple[str, str, dict]]:
    """Return (domain_key, theorem_name, theorem_data) tuples."""
    if not REGISTRY_PATH.exists():
        return []
    with open(REGISTRY_PATH) as f:
        reg = json.load(f)
    params = []
    for dkey, ddata in reg.get("domains", {}).items():
        for theorem in ddata["theorems"]:
            params.append((dkey, theorem["name"], theorem))
    return params


# Pre-compute param lists at collection time
_DOMAIN_KEYS = _domain_keys()
_ENTITY_PARAMS = _entity_params()
_THEOREM_PARAMS = _theorem_params()


# ── Registry structure tests ────────────────────────────────────────────────


class TestRegistryStructure:
    """Validate the registry file itself is well-formed."""

    def test_registry_exists(self):
        assert REGISTRY_PATH.exists(), "Registry not found. Run: python scripts/harvest_test_registry.py"

    def test_registry_has_meta(self, registry):
        assert "_meta" in registry
        meta = registry["_meta"]
        assert meta["n_domains"] == 24
        assert meta["n_entities_total"] == 288  # 24 × 12
        assert meta["n_theorems_total"] == 144  # 24 × 6

    def test_registry_global_summary(self, registry):
        gs = registry["global_summary"]
        assert gs["all_integrity_bounds_satisfied"]
        assert gs["max_duality_residual"] < 1e-12
        assert gs["max_log_integrity_residual"] < 1e-10

    @pytest.mark.parametrize("domain_key", _DOMAIN_KEYS, ids=lambda k: k)
    def test_domain_has_12_entities(self, registry, domain_key):
        assert registry["domains"][domain_key]["n_entities"] == 12

    @pytest.mark.parametrize("domain_key", _DOMAIN_KEYS, ids=lambda k: k)
    def test_domain_has_8_channels(self, registry, domain_key):
        assert registry["domains"][domain_key]["n_channels"] == 8

    @pytest.mark.parametrize("domain_key", _DOMAIN_KEYS, ids=lambda k: k)
    def test_domain_has_4_categories(self, registry, domain_key):
        entities = registry["domains"][domain_key]["entities"]
        cats = {e["category"] for e in entities}
        assert len(cats) == 4

    @pytest.mark.parametrize("domain_key", _DOMAIN_KEYS, ids=lambda k: k)
    def test_domain_has_6_theorems(self, registry, domain_key):
        assert len(registry["domains"][domain_key]["theorems"]) == 6


# ── Entity catalog tests ───────────────────────────────────────────────────


class TestEntityCatalog:
    """Validate entity structure from registry data."""

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_trace_vector_shape(self, domain_key, entity_name, entity):
        assert len(entity["trace_vector"]) == 8

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_trace_vector_bounds(self, domain_key, entity_name, entity):
        c = entity["trace_vector"]
        assert all(0.0 <= v <= 1.0 for v in c)


# ── Tier-1 identity tests (from registry values) ───────────────────────────


class TestTier1Identities:
    """Verify Tier-1 kernel identities from precomputed registry values.

    These tests validate that the registry itself records conformant values.
    No kernel recomputation needed.
    """

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_duality_identity(self, domain_key, entity_name, entity):
        """F + ω = 1 (duality identity, verified from registry)."""
        k = entity["kernel"]
        assert abs(k["F"] + k["omega"] - 1.0) < 1e-12

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_integrity_bound(self, domain_key, entity_name, entity):
        """IC ≤ F (integrity bound, verified from registry)."""
        k = entity["kernel"]
        assert k["IC"] <= k["F"] + 1e-12

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_log_integrity_relation(self, domain_key, entity_name, entity):
        """IC = exp(κ) (log-integrity relation, verified from registry)."""
        k = entity["kernel"]
        assert abs(k["IC"] - math.exp(k["kappa"])) < 1e-10


# ── Theorem tests (from registry) ──────────────────────────────────────────


class TestTheorems:
    """Verify all theorems pass from registry data."""

    @pytest.mark.parametrize(
        "domain_key,theorem_name,theorem",
        _THEOREM_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_theorem_passed(self, domain_key, theorem_name, theorem):
        assert theorem["passed"], f"{theorem_name} failed in {domain_key}"

    @pytest.mark.parametrize("domain_key", _DOMAIN_KEYS, ids=lambda k: k)
    def test_all_domain_theorems_pass(self, registry, domain_key):
        theorems = registry["domains"][domain_key]["theorems"]
        for t in theorems:
            assert t["passed"], f"{t['name']} failed"


# ── Regime classification tests ─────────────────────────────────────────────


class TestRegimeClassification:
    """Verify regime labels are valid."""

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_regime_is_valid(self, domain_key, entity_name, entity):
        assert entity["kernel"]["regime"] in ("Stable", "Watch", "Collapse")


# ── Live verification (optional, heavyweight) ──────────────────────────────

_LIVE = os.environ.get("UMCP_LIVE_REGISTRY", "0") == "1"


@pytest.mark.skipif(not _LIVE, reason="Set UMCP_LIVE_REGISTRY=1 to run live checks")
class TestLiveVerification:
    """Recompute kernel for every entity and verify registry matches.

    Only runs when UMCP_LIVE_REGISTRY=1 environment variable is set.
    This is the heavyweight check that confirms the registry is current.
    """

    @pytest.mark.parametrize(
        "domain_key,entity_name,entity",
        _ENTITY_PARAMS,
        ids=lambda p: f"{p[0]}::{p[1]}" if isinstance(p, tuple) else p,
    )
    def test_kernel_matches_registry(self, domain_key, entity_name, entity):
        from umcp.frozen_contract import EPSILON
        from umcp.kernel_optimized import compute_kernel_outputs

        c = np.array(entity["trace_vector"])
        c = np.clip(c, EPSILON, 1.0 - EPSILON)
        w = np.ones(len(c)) / len(c)
        result = compute_kernel_outputs(c, w)

        stored = entity["kernel"]
        assert abs(result["F"] - stored["F"]) < 1e-10, f"F drift: {result['F']} vs {stored['F']}"
        assert abs(result["omega"] - stored["omega"]) < 1e-10
        assert abs(result["S"] - stored["S"]) < 1e-10
        assert abs(result["C"] - stored["C"]) < 1e-10
        assert abs(result["kappa"] - stored["kappa"]) < 1e-10
        assert abs(result["IC"] - stored["IC"]) < 1e-10
