"""
Entity Catalog Generator — Lists entities defined in domain closures.

Scans closure files for entity-like data structures (particles, elements,
organisms, sign systems, etc.) and generates a domain-level entity catalog
page listing all discovered entities with their source modules.

Usage:
    from umcp.hcg.entity_gen import generate_entities_markdown
    from umcp.hcg.extractor import extract_domain_data, scan_closure_entities

    data = extract_domain_data("standard_model")
    entities = scan_closure_entities("standard_model")
    md = generate_entities_markdown(data, entities)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from umcp.hcg.extractor import EntityInfo, SiteData


def generate_entities_markdown(
    data: SiteData,
    entities: list[EntityInfo],
) -> str:
    """Generate markdown catalog of entities for one domain."""
    sections: list[str] = []

    sections.append(f"# Entity Catalog — {data.domain_display}\n")
    sections.append(
        "> Entities are the real-world quantities that become channels "
        "in the trace vector. Each maps to [0,1]^n through the embedding.\n"
    )

    if not entities:
        sections.append(f"*No entity catalogs found in `closures/{data.domain}/`.*\n")
        return "\n".join(sections)

    # Group by source module
    by_module: dict[str, list[EntityInfo]] = {}
    for e in entities:
        by_module.setdefault(e.source_module, []).append(e)

    sections.append(f"**{len(entities)} entities** across **{len(by_module)} modules**\n")

    # Summary table
    sections.append("## Catalog\n")
    sections.append("| Entity | Source Module |")
    sections.append("|--------|-------------|")
    for e in entities:
        sections.append(f"| {e.name} | `{e.source_module}` |")
    sections.append("")

    # Per-module breakdown
    for module, module_entities in by_module.items():
        sections.append(f"## {module.replace('_', ' ').title()}\n")
        sections.append(f"Source: `closures/{data.domain}/{module}.py`\n")
        sections.append(f"**{len(module_entities)} entities**:\n")
        for e in module_entities:
            sections.append(f"- {e.name}")
        sections.append("")

    # Footer
    sections.append("---\n")
    sections.append(f"*Generated by the Headless Contract Gateway (HCG) · Domain: {data.domain} · UMCP v2.3.1*\n")

    return "\n".join(sections)
