"""
Domain Isolator — Produces standalone, hermetic sites for individual domains.

The current Astro build produces one combined site with all 20 domains.
The isolator creates an independent, deployable site for a single domain
that can be pushed to its own repo, Vercel project, or Netlify site.

Architecture:
    isolator reads DomainConfig + SiteData
    → generates a self-contained Astro project (config, package.json, layout, pages)
    → builder populates content into that project
    → npm build produces a hermetic static site

This is the structural mechanism for "a fleet of independent, autonomous websites."
The content is identical to the monolith build; only the packaging changes.

Usage:
    from umcp.hcg.isolator import isolate_domain, IsolatedSite

    site = isolate_domain("finance", output_dir="deploy/finance")
    # site.project_dir → deploy/finance/  (ready for `npm install && npm run build`)

    # Or from CLI:
    python -m umcp.hcg.isolator --domain finance --output deploy/finance
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

from umcp.hcg.builder import build_site
from umcp.hcg.domain_config import DomainConfig, get_domain_config

logger = logging.getLogger(__name__)


@dataclass
class IsolatedSite:
    """Result of isolating a domain into a standalone project."""

    domain: str
    project_dir: Path
    content_dir: Path
    config: DomainConfig
    pages_built: int
    ready: bool  # True if npm install + build would succeed


# ---------------------------------------------------------------------------
# Astro config template for isolated site
# ---------------------------------------------------------------------------

_ASTRO_CONFIG_TEMPLATE = """\
// @ts-check
// Isolated domain site — {display_name}
// Generated by HCG Domain Isolator · UMCP v2.3.1
import {{ defineConfig }} from 'astro/config';
import mdx from '@astrojs/mdx';
import tailwind from '@astrojs/tailwind';

export default defineConfig({{
  site: '{site_url}',
  base: '{base_path}',
  integrations: [mdx(), tailwind()],
  build: {{ format: 'directory' }},
}});
"""

# ---------------------------------------------------------------------------
# Package.json template for isolated site
# ---------------------------------------------------------------------------

_PACKAGE_JSON_TEMPLATE = {
    "name": "gcd-{slug}",
    "type": "module",
    "version": "2.3.1",
    "private": True,
    "scripts": {
        "dev": "astro dev",
        "build": "astro build",
        "preview": "astro preview",
    },
    "dependencies": {
        "astro": "^5.0.0",
        "@astrojs/mdx": "^4.0.0",
    },
    "devDependencies": {
        "@astrojs/tailwind": "^6.0.0",
        "tailwindcss": "^3.4.0",
    },
}

# ---------------------------------------------------------------------------
# Content config (Astro 5 collections) — single-domain variant
# ---------------------------------------------------------------------------

_CONTENT_CONFIG_TEMPLATE = """\
// Content collections for isolated {display_name} site
// Generated by HCG Domain Isolator · UMCP v2.3.1
import {{ defineCollection, z }} from 'astro:content';
import {{ glob }} from 'astro/loaders';

const domainSchema = z.object({{
  title: z.string(),
  description: z.string().optional(),
  domain: z.string().optional(),
  lens: z.string().optional(),
  regime: z.string().optional(),
  pageType: z.string().optional(),
  primaryColor: z.string().optional(),
  accentColor: z.string().optional(),
  icon: z.string().optional(),
  contract: z.string().optional(),
  theoremCount: z.number().optional(),
  entityCount: z.number().optional(),
}});

const domain = defineCollection({{
  loader: glob({{ pattern: '**/*.{{md,mdx}}', base: 'src/content/{slug}' }}),
  schema: domainSchema,
}});

export const collections = {{ domain }};
"""

# ---------------------------------------------------------------------------
# Tailwind config
# ---------------------------------------------------------------------------

_TAILWIND_CONFIG = """\
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        stable: { DEFAULT: '#22c55e', dark: '#166534' },
        watch: { DEFAULT: '#eab308', dark: '#854d0e' },
        collapse: { DEFAULT: '#ef4444', dark: '#991b1b' },
        kernel: {
          50: '#f0f4ff', 100: '#dbe4ff', 200: '#bac8ff',
          300: '#91a7ff', 400: '#748ffc', 500: '#5c7cfa',
          600: '#4c6ef5', 700: '#4263eb', 800: '#3b5bdb',
          900: '#364fc7',
        },
      },
    },
  },
  plugins: [],
};
"""

# ---------------------------------------------------------------------------
# Minimal layout for isolated site
# ---------------------------------------------------------------------------

_BASE_LAYOUT_TEMPLATE = """\
---
/**
 * Base layout for isolated {display_name} site.
 * Generated by HCG Domain Isolator.
 */
interface Props {{
  title?: string;
  description?: string;
  primaryColor?: string;
  accentColor?: string;
}}

const {{
  title = '{display_name}',
  description = '{tagline}',
  primaryColor = '{primary_color}',
  accentColor = '{accent_color}',
}} = Astro.props;
const base = import.meta.env.BASE_URL;
---

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{title}} — GCD Kernel</title>
  <meta name="description" content={{description}} />
  <style>
    :root {{
      --color-primary: {{primaryColor}};
      --color-accent: {{accentColor}};
    }}
  </style>
</head>
<body class="bg-gray-950 text-gray-100 min-h-screen">
  <header class="border-b border-gray-800 px-6 py-4">
    <nav class="max-w-6xl mx-auto flex items-center justify-between">
      <a href={{base}} class="text-xl font-bold" style="color: var(--color-accent)">
        {display_name}
      </a>
      <div class="flex gap-4 text-sm text-gray-400">
        <a href={{base}} class="hover:text-white">Overview</a>
        <a href={{`${{base}}contract/`}} class="hover:text-white">Contract</a>
        <a href={{`${{base}}theorems/`}} class="hover:text-white">Theorems</a>
        <a href={{`${{base}}entities/`}} class="hover:text-white">Entities</a>
      </div>
    </nav>
  </header>
  <main class="max-w-6xl mx-auto px-6 py-8">
    <slot />
  </main>
  <footer class="border-t border-gray-800 px-6 py-4 text-center text-xs text-gray-500">
    <p>
      {display_name} · GCD Kernel v2.3.1 ·
      <em>Collapse is generative; only what returns is real.</em>
    </p>
  </footer>
</body>
</html>
"""

# ---------------------------------------------------------------------------
# Page templates for isolated site
# ---------------------------------------------------------------------------

_INDEX_PAGE = """\
---
import {{ getCollection, render }} from 'astro:content';
import BaseLayout from '../layouts/BaseLayout.astro';

const entries = await getCollection('domain');
const overview = entries.find(e => e.id.endsWith('index'));
const {{ Content }} = overview ? await render(overview) : {{ Content: null }};
---

<BaseLayout>
  {{Content ? <Content /> : <p>No content generated yet.</p>}}
</BaseLayout>
"""

_SUBPAGE_TEMPLATE = """\
---
import {{ getCollection, render }} from 'astro:content';
import BaseLayout from '../layouts/BaseLayout.astro';

const entries = await getCollection('domain');
const page = entries.find(e => e.id.endsWith('{page_name}'));
const {{ Content }} = page ? await render(page) : {{ Content: null }};
---

<BaseLayout title="{page_title}">
  {{Content ? <Content /> : <p>No {page_name} content available.</p>}}
</BaseLayout>
"""


def _resolve_site_url(config: DomainConfig) -> tuple[str, str]:
    """Determine site URL and base path for an isolated domain.

    Returns (site_url, base_path).
    """
    if config.base_url:
        return config.base_url, "/"

    # Default: subpath on GitHub Pages for monorepo, or root for standalone
    if config.deploy_target == "vercel" or config.deploy_target == "netlify":
        return f"https://{config.slug}.gcd-kernel.org", "/"
    else:
        # Standalone GitHub Pages repo
        return "https://calebpruett927.github.io", f"/gcd-{config.slug}/"


def isolate_domain(
    domain: str,
    output_dir: Path | str | None = None,
    *,
    build_content: bool = True,
) -> IsolatedSite:
    """Create a standalone Astro project for one domain.

    Parameters
    ----------
    domain : str
        Domain slug (e.g. "finance").
    output_dir : Path, optional
        Where to create the project. Defaults to deploy/<domain>.
    build_content : bool
        If True, run the builder to populate content. If False, only
        scaffold the project structure (useful for CI where content
        is provided as an artifact).

    Returns
    -------
    IsolatedSite
        Metadata about the created project.
    """
    config = get_domain_config(domain)

    if output_dir is None:
        from umcp.hcg.extractor import _repo_root

        output_dir = _repo_root() / "deploy" / domain
    else:
        output_dir = Path(output_dir)

    project_dir = output_dir
    project_dir.mkdir(parents=True, exist_ok=True)

    site_url, base_path = _resolve_site_url(config)

    # --- Scaffold project structure ---
    src_dir = project_dir / "src"
    content_dir = src_dir / "content" / config.slug
    layouts_dir = src_dir / "layouts"
    pages_dir = src_dir / "pages"

    for d in [content_dir, layouts_dir, pages_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # astro.config.mjs
    astro_config = _ASTRO_CONFIG_TEMPLATE.format(
        display_name=config.display_name,
        site_url=site_url,
        base_path=base_path,
    )
    (project_dir / "astro.config.mjs").write_text(astro_config, encoding="utf-8")

    # package.json
    pkg = dict(_PACKAGE_JSON_TEMPLATE)
    pkg["name"] = f"gcd-{config.slug}"
    (project_dir / "package.json").write_text(json.dumps(pkg, indent=2), encoding="utf-8")

    # content.config.ts
    content_config = _CONTENT_CONFIG_TEMPLATE.format(
        display_name=config.display_name,
        slug=config.slug,
    )
    (src_dir / "content.config.ts").write_text(content_config, encoding="utf-8")

    # tailwind.config.mjs
    (project_dir / "tailwind.config.mjs").write_text(_TAILWIND_CONFIG, encoding="utf-8")

    # Base layout
    layout = _BASE_LAYOUT_TEMPLATE.format(
        display_name=config.display_name,
        tagline=config.tagline,
        primary_color=config.primary_color,
        accent_color=config.accent_color,
    )
    (layouts_dir / "BaseLayout.astro").write_text(layout, encoding="utf-8")

    # Pages
    (pages_dir / "index.astro").write_text(_INDEX_PAGE, encoding="utf-8")

    for page_name, page_title in [
        ("contract", f"Contract — {config.display_name}"),
        ("theorems", f"Theorems — {config.display_name}"),
        ("entities", f"Entities — {config.display_name}"),
    ]:
        page = _SUBPAGE_TEMPLATE.format(
            page_name=page_name,
            page_title=page_title,
        )
        (pages_dir / f"{page_name}.astro").write_text(page, encoding="utf-8")

    # --- Build content ---
    pages_built = 0
    if build_content:
        build_site(domain=domain, output_dir=src_dir / "content")
        # Count generated files
        pages_built = sum(1 for _ in content_dir.rglob("*.md"))

    logger.info(
        "Isolated domain %s → %s (%d pages)",
        domain,
        project_dir,
        pages_built,
    )

    return IsolatedSite(
        domain=domain,
        project_dir=project_dir,
        content_dir=content_dir,
        config=config,
        pages_built=pages_built,
        ready=pages_built > 0,
    )


def isolate_all(
    output_dir: Path | str | None = None,
) -> list[IsolatedSite]:
    """Create standalone projects for all 20 domains.

    Returns list of IsolatedSite objects.
    """
    from umcp.hcg.domain_config import list_domains

    if output_dir is None:
        from umcp.hcg.extractor import _repo_root

        output_dir = _repo_root() / "deploy"
    else:
        output_dir = Path(output_dir)

    results: list[IsolatedSite] = []
    for domain in list_domains():
        try:
            site = isolate_domain(domain, output_dir=output_dir / domain)
            results.append(site)
        except Exception as exc:
            logger.error("Failed to isolate domain %s: %s", domain, exc)

    logger.info("Isolated %d domains → %s", len(results), output_dir)
    return results


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """CLI for the domain isolator."""
    import argparse

    parser = argparse.ArgumentParser(
        prog="hcg-isolator",
        description="HCG Domain Isolator — Create standalone domain sites",
    )
    parser.add_argument(
        "--domain",
        "-d",
        help="Isolate a single domain (e.g. 'finance')",
    )
    parser.add_argument(
        "--all",
        "-a",
        action="store_true",
        dest="isolate_all",
        help="Isolate all 20 domains",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Output directory (default: deploy/<domain>)",
    )
    parser.add_argument(
        "--no-content",
        action="store_true",
        help="Scaffold only — don't generate content",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    output = Path(args.output) if args.output else None

    if args.isolate_all:
        sites = isolate_all(output_dir=output)
        print(f"\nIsolated {len(sites)} domain sites.")
        for s in sites:
            status = "ready" if s.ready else "scaffold only"
            print(f"  {s.domain:30s} {s.pages_built:3d} pages  ({status})")
        return 0

    if args.domain:
        site = isolate_domain(
            args.domain,
            output_dir=output,
            build_content=not args.no_content,
        )
        status = "ready" if site.ready else "scaffold only"
        print(f"Isolated {site.domain} → {site.project_dir} ({site.pages_built} pages, {status})")
        return 0

    print("Specify --domain <name> or --all")
    return 1


if __name__ == "__main__":
    import sys

    sys.exit(main())
