"""
Theorem Page Generator — Lists proven theorems for a domain.

Scans closure files for theorem function definitions and generates
a domain-level theorem catalog page listing all theorems with their
IDs, names, source modules, and proof status.

Usage:
    from umcp.hcg.theorem_gen import generate_theorems_markdown
    from umcp.hcg.extractor import extract_domain_data, scan_closure_theorems

    data = extract_domain_data("standard_model")
    theorems = scan_closure_theorems("standard_model")
    md = generate_theorems_markdown(data, theorems)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from umcp.hcg.extractor import SiteData, TheoremInfo


def generate_theorems_markdown(
    data: SiteData,
    theorems: list[TheoremInfo],
) -> str:
    """Generate markdown catalog of theorems for one domain."""
    sections: list[str] = []

    sections.append(f"# Theorems — {data.domain_display}\n")
    sections.append("> Every theorem derives from Axiom-0. Classical results emerge as degenerate limits.\n")

    if not theorems:
        sections.append(f"*No theorem functions found in `closures/{data.domain}/`.*\n")
        return "\n".join(sections)

    # Group by source module
    by_module: dict[str, list[TheoremInfo]] = {}
    for t in theorems:
        by_module.setdefault(t.source_module, []).append(t)

    sections.append(f"**{len(theorems)} theorems** across **{len(by_module)} modules**\n")

    # Summary table
    sections.append("## Catalog\n")
    sections.append("| ID | Name | Module |")
    sections.append("|----|------|--------|")
    for t in theorems:
        sections.append(f"| `{t.theorem_id}` | {t.name} | `{t.source_module}` |")
    sections.append("")

    # Per-module breakdown
    for module, module_theorems in by_module.items():
        sections.append(f"## {module.replace('_', ' ').title()}\n")
        sections.append(f"Source: `closures/{data.domain}/{module}.py`\n")
        for t in module_theorems:
            sections.append(f"### {t.theorem_id}: {t.name}\n")
            if t.function_name:
                sections.append(f"- **Function**: `{t.function_name}()`")
            sections.append(f"- **Module**: `{t.source_module}`")
            sections.append("")

    # Footer
    sections.append("---\n")
    sections.append(f"*Generated by the Headless Contract Gateway (HCG) · Domain: {data.domain} · UMCP v2.3.1*\n")

    return "\n".join(sections)
